In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [45]:
years = range(1991, 2022)

In [4]:
url_start = 'https://www.basketball-reference.com/awards/awards_{}.html'

# Saving all the pages in the mvp DIR
for year in years:
    url = url_start.format(year)
    data = requests.get(url)
    with open('C:/Users/User/PycharmProjects/scraping/mvp/{}.html'.format(year), 'w+', encoding='utf-8') as f:
        f.write(data.text)

In [16]:
# Scraping the information from the html page and saving into a list
dfs = []
for year in years:
    with open('C:/Users/User/PycharmProjects/scraping/NBA_MVP_PROJECT/mvp/{}.html'.format(year), encoding='utf-8') as f:
        page = f.read()
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_='over_header').decompose()
    mvp_table = soup.find(id='mvp')
    mvp = pd.read_html(str(mvp_table))[0]
    mvp['year'] = year
    dfs.append(mvp)

In [17]:
mvps = pd.concat(dfs)

In [18]:
mvps.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 474 entries, 0 to 14
Data columns (total 21 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     474 non-null    object
 1   Player   474 non-null    object
 2   Age      474 non-null    int64
 3   Tm       474 non-null    object
 4   First    474 non-null    float64
 5   Pts Won  474 non-null    float64
 6   Pts Max  474 non-null    int64
 7   Share    474 non-null    float64
 8   G        474 non-null    int64
 9   MP       474 non-null    float64
 10  PTS      474 non-null    float64
 11  TRB      474 non-null    float64
 12  AST      474 non-null    float64
 13  STL      474 non-null    float64
 14  BLK      474 non-null    float64
 15  FG%      474 non-null    float64
 16  3P%      463 non-null    float64
 17  FT%      474 non-null    float64
 18  WS       474 non-null    float64
 19  WS/48    474 non-null    float64
 20  year     474 non-null    int64
dtypes: float64(14), int64(4), object(3)
memory usage: 81.5+ KB

In [19]:
# Saving the table in csv
mvps.to_csv('C:/Users/User/PycharmProjects/scraping/NBA_MVP_PROJECT/mvp/mvps.csv')

In [20]:
df = pd.read_csv('C:/Users/User/PycharmProjects/scraping/NBA_MVP_PROJECT/mvp/mvps.csv', header=0)

In [54]:
df.head()

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,year
0,0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991

In [11]:
# Selenium is used when we need to scrap a page that contains JS function
from selenium import webdriver

In [12]:
driver = webdriver.Chrome(executable_path='C:/Users/User/Documents/chromedriver_win32/chromedriver')

C:\Users\User\AppData\Local\Temp\ipykernel_5952\595778159.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path='C:/Users/User/Documents/chromedriver_win32/chromedriver')

In [68]:
for year in years:
    url = player_status_url.format(year)

    driver.get(url)
    driver.execute_script('window.scrollTo(1, 10000)')
    time.sleep(2)

    html = driver.page_source
    with open('C:/Users/User/PycharmProjects/scraping/NBA_MVP_PROJECT/player/{}.html'.format(year),'w+', encoding='utf-8') as f:
        f.write(html)

In [22]:
dfs = []
for year in years:
    with open('C:/Users/User/PycharmProjects/scraping/NBA_MVP_PROJECT/player/{}.html'.format(year), encoding='utf-8') as f:
        page = f.read()

    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_='thead').decompose()
    player_table = soup.find_all(id='per_game_stats')[0]
    player_df = pd.read_html(str(player_table))[0]
    player_df['year'] = year
    dfs.append(player_df)

In [23]:
players = pd.concat(dfs)

In [27]:
players

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,year
0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,536,Delon Wright,PG,28,SAC,27,8,25.8,3.9,8.3,...,1.0,2.9,3.9,3.6,1.6,0.4,1.3,1.1,10.0,2021
726,537,Thaddeus Young,PF,32,CHI,68,23,24.3,5.4,9.7,...,2.5,3.8,6.2,4.3,1.1,0.6,2.0,2.2,12.1,2021
727,538,Trae Young,PG,22,ATL,63,63,33.7,7.7,17.7,...,0.6,3.3,3.9,9.4,0.8,0.2,4.1,1.8,25.3,2021
728,539,Cody Zeller,C,28,CHO,48,21,20.9,3.8,6.8,...,2.5,4.4,6.8,1.8,0.6,0.4,1.1,2.5,9.4,2021
729,540,Ivica Zubac,C,23,LAC,72,33,22.3,3.6,5.5,...,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0,2021

In [28]:
players.to_csv('C:/Users/User/PycharmProjects/scraping/NBA_MVP_PROJECT/player/players.csv')

In [29]:
team_stats_url = 'https://www.basketball-reference.com/leagues/NBA_{}_standings.html'

In [36]:
for year in years:
    url = team_stats_url.format(year)

    data = requests.get(url)
    with open('C:/Users/User/PycharmProjects/scraping/NBA_MVP_PROJECT/team/{}.html'.format(year),'w+', encoding='utf-8') as f:
        f.write(data.text)

In [46]:
dfs = []
for year in years:
    with open('C:/Users/User/PycharmProjects/scraping/NBA_MVP_PROJECT/team/{}.html'.format(year), encoding='utf-8') as f:
        page = f.read()

    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_='thead').decompose()
    team_table = soup.find(id='divs_standings_E')
    team = pd.read_html(str(team_table))[0]
    team['year'] = year
    team['Team'] = team['Eastern Conference']
    del team['Eastern Conference']
    dfs.append(team)
    
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_='thead').decompose()
    team_table = soup.find(id='divs_standings_W')
    team = pd.read_html(str(team_table))[0]
    team['year'] = year
    team['Team'] = team['Western Conference']
    del team['Western Conference']
    dfs.append(team)

In [48]:
teams = pd.concat(dfs)

In [49]:
teams

     W   L  W/L%    GB   PS/G   PA/G    SRS  year                  Team
0   56  26  .683     â€”  111.5  105.7   5.22  1991       Boston Celtics*
1   44  38  .537  12.0  105.4  105.6  -0.39  1991   Philadelphia 76ers*
2   39  43  .476  17.0  103.1  103.3  -0.43  1991      New York Knicks*
3   30  52  .366  26.0  101.4  106.4  -4.84  1991    Washington Bullets
4   26  56  .317  30.0  102.9  107.5  -4.53  1991       New Jersey Nets
..  ..  ..   ...   ...    ...    ...    ...   ...                   ...
13  42  30  .583     â€”  112.4  110.2   2.26  2021     Dallas Mavericks*
14  38  34  .528   4.0  113.3  112.3   1.07  2021    Memphis Grizzlies*
15  33  39  .458   9.0  111.1  112.8  -1.58  2021     San Antonio Spurs
16  31  41  .431  11.0  114.6  114.9  -0.20  2021  New Orleans Pelicans
17  17  55  .236  25.0  108.8  116.7  -7.50  2021       Houston Rockets

[1033 rows x 9 columns]

In [50]:
teams.to_csv('C:/Users/User/PycharmProjects/scraping/NBA_MVP_PROJECT/team/teams.csv')